INSERT INTO descriptions (field_name, description_text) VALUES
    ("turn_off_command", "Turns off the bot"),
    ("create_template_command", "Creates a template for you to use later. Only 3 templates are registered per user"),
    ("template_option", "A template you want uploaded. Clear image that you will want your fields to appear on"),
    ("template_number_option", "An id of which template spot to use. Possible template ids are 1, 2 or 3"),
    ("view_command", "Shows your current templates. Without a template number given, will list them, but not show any"),
    ("show_fields_option", "Set this to True to see where your fields are on the template"),
    ("add_field_command", "Adds a field to a template"),
    ("field_type_option", "You can make it either image field or text field"),
    ("name_option", "What would you like to name your field"),
    ("top_bound_option", "The uppermost pixel of the image for the field area (top left is (0,0))"),
    ("left_bound_option", "The leftmost pixel of the image for the field area (top left is (0,0))"),
    ("down_bound_option", "The lowest pixel of the image for the field area (top left corner is (0,0))"),
    ("right_bound_option", "The rightmost pixel of the image for the field area (top left corner is (0,0))"),
    ("reference_image_option", "The image with marked rectangle field. Make sure to fill the rectangle in"),
    ("reference_color_option", "The color you used to reference the field for the image. Use hexadecimal RGB color code"),
    ("remove_field_command", "Removes a field with a given name from a template"),
    ("field_name_option", "A name for the field. Use /view with option show_fields=True to list your fields"),
    ("use_template_command", "Initialize using template by filling its fields"),
    ("fill_text_field_command", "Fill out a text field that you have registered for your command"),
    ("text_option", "What text you want to write on your field"),
    ("font_option", "What font style would you like to use?"),
    ("font_size_option", "What font size would you like to use? This scales lineary and default is 3"),
    ("color_option", "What color do you want your text to be in? Use hexadecimal RGB color code"),
    ("fill_image_field_command", "Fill out an image field that you have registered for your command"),
    ("image_option", "Upload an image that you would like to put in your image field")
;